  version: '3'

  services:
    db:
      image: postgres
      volumes:
        - ./postgres-data:/var/lib/postgresql/data
      ports:
        - "5432:5432"
      environment:
        - POSTGRES_DB=social_slam_db
        - POSTGRES_USER=social_slam_admin
        - POSTGRES_PASSWORD=social_slamming_2020
    web:
      build: .
      image: 385867774100.dkr.ecr.eu-central-1.amazonaws.com/social-slam-api:latest
      links:
        - db:db
      command: ./run_staging.sh
      ports:
        - "8000:8000"
      depends_on:
        - db
