  version: '3'

  services:
    db:
      image: postgres
      ports:
        - "5432:5432"
      logging:
        driver: awslogs
        options:
          awslogs-region: eu-central-1
          awslogs-group: /ecs/social_slam_api
          awslogs-stream-prefix: compose_test
      environment:
        - POSTGRES_DB=social_slam_db
        - POSTGRES_USER=social_slam_admin
        - POSTGRES_PASSWORD=social_slamming_2020
    web:
      build: .
      image: 385867774100.dkr.ecr.eu-central-1.amazonaws.com/social-slam-api:latest
      links:
        - db:db
      logging:
        driver: awslogs
        options:
          awslogs-region: eu-central-1
          awslogs-group: /ecs/social_slam_api
          awslogs-stream-prefix: compose_test
      command: >
        bash -c "python manage.py makemigrations
        && python manage.py migrate
        && python manage.py runserver 0.0.0.0:8000"
#      volumes:
#        - .:/code
      ports:
        - "8000:8000"
