name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  AWS_REGION: eu-central-1
  CONTAINER_TAG: pr-${{ github.event.number }}
  CONTAINER_IMAGE: ${{ secrets.AWS_ECR_REPOSITORY }}:pr-${{ github.event.number }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{env.AWS_REGION}}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build image
        run: |
          docker build \
          --cache-from ${{ steps.login-ecr.outputs.registry }}/${{ secrets.AWS_ECR_REPOSITORY }}:latest \
          --cache-from ${{ steps.login-ecr.outputs.registry }}/${{ env.CONTAINER_IMAGE }} \
          --tag $CONTAINER_IMAGE \
          --tag ${{ steps.login-ecr.outputs.registry }}/$CONTAINER_IMAGE \
          ./social_slam_api

      - name: Push docker image
        run: |
          docker push ${{ steps.login-ecr.outputs.registry }}/$CONTAINER_IMAGE

  deploy:
    needs: build
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{env.AWS_REGION}}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Re-tag image
        run: |
          MANIFEST=$(aws ecr batch-get-image --repository-name ${{ steps.login-ecr.outputs.registry }} --image-ids imageTag=${{env.CONTAINER_TAG}} --query 'images[].imageManifest' --output text)
          aws ecr put-image --repository-name ${{ secrets.AWS_ECR_REPOSITORY }} --image-tag latest --image-manifest "$MANIFEST"
